# Generated by Django 4.2 on 2023-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photojournal',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
