# Generated by Django 4.2 on 2023-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_photojournal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photojournal',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
