# Generated by Django 4.2 on 2023-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_photojournal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photojournal',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='photojournal',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
